# Pytorch beginner course: Optimizer

## Summary

- [Simple training](#simple-training)
- [Optimizer](#optimizer)
    - [Gradient Descent Algorithm](#gradient-descent-algorithm)
- [Glossary of the used tools](#glossary-of-the-used-tools)
    - [Methods](#methods)
    - [Properties](#properties)
- [References](#references)
- [Author](#author)

## Simple training

Before to introduce the backpropagation concept we will implement a simple code that simulate a training scenario using only the knowledge acquired at this point of the course.

To understand the concept the best way is proced step by step, so in this first version of our code we will implement only the main parts of a trainer

In [32]:
import torch

# Tensor that contain our weights
weights = torch.ones(4, dtype=torch.float64, requires_grad=True)

# Define a function to get a model with their weights
model = (weights*3).sum()

# Apply the backward on our model to compute the gradient
model.backward()

# output of the weights gradient
print(weights.grad)

tensor([3., 3., 3., 3.], dtype=torch.float64)


as we can see, in output we have tensor with all values of the gradient are equals to $3$ and this means that the gradients of our weights tensor are equal to $3$.
Now we will see what happens if we iterate the training for the model for $3 epochs$ for instance

In [33]:
# Tensor that contain our weights
weights = torch.ones(4, dtype=torch.float64, requires_grad=True)

for epochs in range(3):
    model = (weights*3).sum()
    model.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.], dtype=torch.float64)
tensor([6., 6., 6., 6.], dtype=torch.float64)
tensor([9., 9., 9., 9.], dtype=torch.float64)


as we can see at each iteration the gradients calculation accumulates and we get a clearly wrong gradient coordinates, so to fix this bad accumulation we must set to zero the gradient value at each epoch

In [34]:
# Tensor that contain our weights
weights = torch.ones(4, dtype=torch.float64, requires_grad=True)

for epochs in range(3):
    model = (weights*3).sum()
    model.backward()
    print(weights.grad)

    # set to zero the gradient values
    weights.grad.zero_()

tensor([3., 3., 3., 3.], dtype=torch.float64)
tensor([3., 3., 3., 3.], dtype=torch.float64)
tensor([3., 3., 3., 3.], dtype=torch.float64)


Now the gradients computation is correctly and remember that you must pay attention to this details to avoid to get a bad model.

## Optimizer

One of the most important tool about the machine learning algorithms is the **optimizer**, we know that the our goal consist in the *loss function minimization* and to do this we can use specific algorithms, based on the famous ***descent gradient algorithm***, we can use this kind of algorithms because our loss function is derivable.

Hence, we use an optimizer algorithms to minimize the loss function, and this optimizers usually are iterative algorithm based on a *gradient descent algorithm*, the aim of the optimizers is update the parameters of our model with the loss minimization.

The most famous optimizer used in machine learning are:

* *Stochastic Gradient Descent (SGD)*
* *Adaptive moment Estimation (ADAM)*

### Gradient Descent Algorithm

The gradient descent is the most important iterative algorithm to find the minima of a function, mathematically we explain the essence of the gradient descent as:

$$
x_{k+1} = x_k - \alpha \nabla f(x_k)
$$

⚠️: The quantity $\alpha$ is so called ***learning rate*** and this value is a huge influence on the final result.

As follow we can see also the ***backtracking*** approach to choose a different values for $\alpha$ at each iteration to optimize the algorithm.

At begin we set the $\alpha_{k}$ as:

$$
\alpha_{k} = 1
$$

Now we can compute the value of the $x_{k+1}$:

$$
X = x_k - \nabla f(x_k)
$$

Now we must a check on the $X$, so if:

$$
f(X) \leq f(x_k)-\frac{\alpha_k}{3} ||\nabla f(x_k)||
$$

then:

$$
x_{k+1} = X
$$

otherwise, we apply the backtracking and to do this we return at previous index but with decreased value for $\alpha$ *(learning rate)*, hence:

$$
\alpha_k = 0.5

X = x_k - 0.5 \nabla f(x_k)
$$

and so on...

## Glossary of the used tools

### Methods

- `torch.zero_()`

### Properties

- `torch.autograd.grad`

## References

[Pytorch documentation](https://pytorch.org/docs/stable/index.html)

## Author

Emilio Garzia, 2024

[Github](https://github.com/EmilioGarzia)

[Linkedin](https://www.linkedin.com/in/emilio-garzia-58a934294/)